#!/usr/bin/env ruby
# frozen_string_literal: true

require "bundler/setup"
require "log_reader"

def request_argument
  warn "please provide a file path, ex, #{File.basename($PROGRAM_NAME)} /some/file.log"

  exit 1
end

file_path = ARGV[0] or request_argument

begin
  reader = LogReader::Parser.new(file_path)
  puts reader.format
rescue LogReader::Error => e
  warn "Couldn't parse log: #{e.message}"

  exit 2
end
